echo "[server]" > inventory
cat vps.inventory >> inventory
echo "" >> inventory
echo "[etcd]" >> inventory
echo "vps1" >> inventory
echo "vps2" >> inventory
echo "vps3" >> inventory
echo "" >> inventory
echo "[patroni]" >> inventory
echo "vps1" >> inventory
echo "vps2" >> inventory
echo "vps3" >> inventory
echo "" >> inventory
echo "[keepalived]" >> inventory
echo "vps1" >> inventory
echo "vps2" >> inventory
echo "vps3" >> inventory
echo "" >> inventory
echo "[haproxy]" >> inventory
echo "vps1" >> inventory
echo "vps2" >> inventory
echo "vps3" >> inventory
echo "" >> inventory