echo "[server]" > inventory
cat haproxy.inventory >> inventory
cat nginx.inventory >> inventory
echo "" >> inventory
echo "[haproxy]" >> inventory
echo "haproxy1" >> inventory
echo "haproxy2" >> inventory
echo "" >> inventory
echo "[keepalived]" >> inventory
echo "haproxy1" >> inventory
echo "haproxy2" >> inventory
echo "" >> inventory
echo "[nginx]" >> inventory
echo "nginx1" >> inventory
echo "nginx2" >> inventory