---
- name: update package
  hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: m4eba.common.update_package_cache

- name: disable swap
  hosts: k8s_controller, k8s_worker
  tasks:
    - ansible.builtin.import_role:
        name: m4eba.common.disable_swap
