echo "[server]" > inventory
cat controller.inventory >> inventory
cat worker.inventory >> inventory
echo "" >> inventory
echo "[etcd]" >> inventory
echo "controller1" >> inventory
echo "controller2" >> inventory
echo "" >> inventory
echo "[haproxy]" >> inventory
echo "controller1" >> inventory
echo "controller2" >> inventory
echo "" >> inventory
echo "[keepalived]" >> inventory
echo "controller1" >> inventory
echo "controller2" >> inventory
echo "" >> inventory
echo "[k8s_controller]" >> inventory
echo "controller1" >> inventory
echo "controller2" >> inventory
echo "" >> inventory
echo "[k8s_worker]" >> inventory
echo "worker1" >> inventory
echo "worker2" >> inventory